{
  "tracks": {
    "href": "https://api.spotify.com/v1/search?query=abba&type=track&market=US&offset=0&limit=1",
    "items": [
      {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/0LcJLqbBmaGUft1e9Mm8HV"
              },
              "href": "https://api.spotify.com/v1/artists/0LcJLqbBmaGUft1e9Mm8HV",
              "id": "0LcJLqbBmaGUft1e9Mm8HV",
              "name": "ABBA",
              "type": "artist",
              "uri": "spotify:artist:0LcJLqbBmaGUft1e9Mm8HV"
            }
          ],
          "available_markets": [
            "AD",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "EC",
            "EE",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JP",
            "LI",
            "LT",
            "LU",
            "LV",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "PA",
            "PE",
            "PH",
            "PL",
            "PT",
            "PY",
            "RO",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/1M4anG49aEs4YimBdj96Oy"
          },
          "href": "https://api.spotify.com/v1/albums/1M4anG49aEs4YimBdj96Oy",
          "id": "1M4anG49aEs4YimBdj96Oy",
          "images": [
            {
              "height": 575,
              "url": "https://i.scdn.co/image/de30d4da9efd1b491493ed288e09b6f935ff10ab",
              "width": 640
            },
            {
              "height": 270,
              "url": "https://i.scdn.co/image/b8e2ae77e9379d27e33f39d2c2643cb52de1b8ac",
              "width": 300
            },
            {
              "height": 57,
              "url": "https://i.scdn.co/image/a346fc150b229c7818029110858b3d915cf9400e",
              "width": 63
            }
          ],
          "name": "Arrival",
          "release_date": "1976",
          "release_date_precision": "year",
          "type": "album",
          "uri": "spotify:album:1M4anG49aEs4YimBdj96Oy"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/0LcJLqbBmaGUft1e9Mm8HV"
            },
            "href": "https://api.spotify.com/v1/artists/0LcJLqbBmaGUft1e9Mm8HV",
            "id": "0LcJLqbBmaGUft1e9Mm8HV",
            "name": "ABBA",
            "type": "artist",
            "uri": "spotify:artist:0LcJLqbBmaGUft1e9Mm8HV"
          }
        ],
        "available_markets": [
          "AD",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "EC",
          "EE",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IS",
          "IT",
          "JP",
          "LI",
          "LT",
          "LU",
          "LV",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "PA",
          "PE",
          "PH",
          "PL",
          "PT",
          "PY",
          "RO",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 230693,
        "explicit": false,
        "external_ids": {
          "isrc": "SEAYD7601020"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/4NtUY5IGzHCaqfZemmAu56"
        },
        "href": "https://api.spotify.com/v1/tracks/4NtUY5IGzHCaqfZemmAu56",
        "id": "4NtUY5IGzHCaqfZemmAu56",
        "is_local": false,
        "name": "Dancing Queen",
        "popularity": 69,
        "preview_url": null,
        "track_number": 2,
        "type": "track",
        "uri": "spotify:track:4NtUY5IGzHCaqfZemmAu56"
      }
    ],
    "limit": 1,
    "next": "https://api.spotify.com/v1/search?query=abba&type=track&market=US&offset=1&limit=1",
    "offset": 0,
    "previous": null,
    "total": 9001
  }
}
